### ISSUE TITLE
Missing release for comment feature to work

### ISSUE THREAD

**Issue by baywet** [eps1lon/actions-label-merge-conflict#25]
Hey @eps1lon 
It seems you forgot to release (tag) since the merge of the pull request.
https://github.com/eps1lon/actions-label-merge-conflict/compare/v1.4.0...main
Can you release 1.5.0 please? Thanks!

**Comment by baywet** [comment]
See the result it's giving at the moment https://github.com/microsoftgraph/microsoft-graph-docs/pull/9290/checks?check_run_id=920335567

**Comment by eps1lon** [comment]
Sure but I recommend installing a branch anyway. Tags aren't required to install an action.

**Comment by baywet** [comment]
Now that you're mentioning it, I'm actually using the releases/1.x branch but it's behind main.
https://github.com/eps1lon/actions-label-merge-conflict/compare/releases/1.x...main

**Comment by eps1lon** [comment]
Released [2.0.0](https://github.com/eps1lon/actions-label-merge-conflict/releases/tag/v2.0.0).
