### ISSUE TITLE
Add custom notification mechanism

### ISSUE THREAD

**Issue by Younes-Charfaoui** [eps1lon/actions-label-merge-conflict#89]
Thanks a lot for your Github action; it is mighty!

I wanted to ask if we can have custom mechanisms for notifying these results to the respected developers (Author and reviewers if possible) via different means (Like email, slack, or any other thing).

Currently, the only way to notify the author is via email (after the bot comment).

It will be fantastic also when the author fixes the PR => To notify the reviewers in this PR, i.e. `commentOnClean`

Either we can have our own custom `commentOnClean` and `commentOnDirty` actions, or you can share the result from your action to use it in a different job or step to do custom notification!

Thanks a lot @eps1lon

**Comment by eps1lon** [comment]
This action uses labels as an abstraction over notifications. When labels change, notifications are send by GitHub.

How these notifications are handled is up to the involved people (e.g. E-Mail filters). 

For different channels, you should compose your workflow with other actions. Using anything other than GitHub labels is out-of-scope for this action.
