### ISSUE TITLE
The set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by MZole** [eps1lon/actions-label-merge-conflict#93]
The set-output command is [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and will be disabled soon.

We are using this workflow in one of our actions in [this action](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/check-merge-conflict/action.yml#L9). This action is referenced in our projects and it generates the warning for example on [line 31](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3316066373/jobs/5477422558) under `Check for Merge Conflict in PR` in the jobs.

This issue already has a [pull request](https://github.com/eps1lon/actions-label-merge-conflict/pull/92), I just want to ensure it is not missed.

**Comment by Piedone** [comment]
Furthermore, there's also a deprecation warning about Node:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: eps1lon/actions-label-merge-conflict

**Comment by NotMyFault** [comment]
I took care about that in https://github.com/eps1lon/actions-label-merge-conflict/pull/92, and the Node.js deprecation in https://github.com/eps1lon/actions-label-merge-conflict/pull/90.

Just awaiting a new release of this action 👏🏻

**Comment by Piedone** [comment]
Awesome, thank you! @MZole could you please check the latest release?

**Comment by eps1lon** [comment]
Released as 2.1.0 and on the 2.x branch. @NotMyFault thanks for working on this!
