### ISSUE TITLE
No label added

### ISSUE THREAD

**Issue by schotti1001** [eps1lon/actions-label-merge-conflict#98]
I added the example code in a new .yml file in the .github/workflows folder. 
The job is displayed in the pull requests, but always finishes successfully after 1 second, but there are definitely merge conflicts to the base branch.
I know this description is quite vague but maybe somebody has a idea what i am doing wrong

**Comment by eps1lon** [comment]
Can you link the repo and PRs in question?

**Comment by eps1lon** [comment]
Sorry but we can't debug private repos.

**Comment by Lutzifer** [comment]
@eps1lon I tested this with a public repo and it works there: https://github.com/num42/merge_labels_example

Are there any additional steps necessary for private repos?
